### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by richardleggett** [localz/spotz-push-sdk-android#1]
README gradle section refers to:

`compile 'com.localz.spotzpush.sdk:spotz-push-sdk:1.1.1@aar'`

Gradle could not find this artefact in the maven repo, instead I think it should be this?:

`compile 'com.localz.spotzpush.sdk:spotz-push-sdk-gcm:1.1.1@aar'`

Also there's a newer version:

`compile 'com.localz.spotzpush.sdk:spotz-push-sdk-gcm:1.1.2@aar'`

**Comment by gyamana** [comment]
Cheers for that, will fix that up now
