### ISSUE TITLE
Ability to retry 

### ISSUE THREAD

**Issue by richardleggett** [localz/spotz-push-sdk-android#2]
If `SpotzPushService.init()` fails, due to flaky mobile internet for example. There doesn't seem to be a way to retry (e.g. call it again)? At this point we'd have to `System.exit()` the app because we require `deviceId` to be populated before continuing to use the app, normally I'd present the user with a retry option. Is there any mechanism to reset and retry the initialization?

**Comment by gyamana** [comment]
Hi Richard, will modify so that you can call the init method again if the device registration request fails.

**Comment by gyamana** [comment]
Please use latest SDK version 1.1.8. Re-initialising the SDK will now retry the initialisation.
